name: Template

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Download cargo-generate
        run: |
          curl -L https://github.com/cargo-generate/cargo-generate/releases/download/v0.8.0/cargo-generate-v0.8.0-x86_64-unknown-linux-musl.tar.gz | tar zxf -
      - name: Add cargo-generate to PATH
        run: echo "./cargo-generate" >> $GITHUB_PATH
      - name: Run cargo-generate
        run: cargo generate --git https://github.com/ark0f/rust-ark0f-template --name github-ci-test
